--Q1. What is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount) AS revenue
From `airy-charmer-468922-c4.customer_behavior.Customer`
group by gender;

-- Q2. Discount used, but spent more than average purchase amount
SELECT
  `Customer ID` AS customer_id,
  `Purchase_Amount` AS purchase_amount
FROM `airy-charmer-468922-c4.customer_behavior.Customer`
WHERE `Discount Applied` = TRUE
  AND `Purchase_Amount` >= (
    SELECT AVG(`Purchase_Amount`)
    FROM `airy-charmer-468922-c4.customer_behavior.Customer`
  )
  order by customer_id;

--Q3. Which are the top 5 products with the highest average review rating? 
select `Item Purchased`, round(Avg(`Review Rating`),2) as `Average Product Rating`
from `customer_behavior.Customer`
group by `Item Purchased`
order by avg(`Review Rating`) desc
limit 5;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select `Shipping Type`, round(avg(`Purchase_Amount`),2)
from `customer_behavior.Customer`
where `Shipping Type` in ('Standard' , 'Express')
group by `Shipping Type`;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select `Subscription Status`, Count (`Customer ID`) as `Total Customers`, round(avg(`Purchase_Amount`),2) as `Average Spend`, round(sum(`Purchase_Amount`),2) as `Total Revenue`
from `customer_behavior.Customer`
group by `Subscription Status`
order by `Total Revenue`, `Average Spend` desc;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied? 
select `Item Purchased`, Round(100*sum(case when `Discount Applied` = TRUE then 1 else 0 end)/count(*) ,2) as `Discount Rate`
from `customer_behavior.Customer`
group by `Item Purchased`
order by `Discount Rate` desc
limit 5;
--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
SELECT
  CASE
    WHEN `Previous Purchases` = 1 THEN 'New'
    WHEN `Previous Purchases` BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
  END AS customer_segment,
  COUNT(*) AS customer_count
FROM `customer_behavior.Customer`
GROUP BY customer_segment
ORDER BY customer_count DESC;

--Q8. What are the top 3 most purchased products within each category?
WITH product_counts AS (
  SELECT
    Category,
    `Item Purchased`,
    COUNT(*) AS purchase_count,
    ROW_NUMBER() OVER (
      PARTITION BY Category
      ORDER BY COUNT(`Customer ID`) DESC
    ) AS `Item Rank`
  FROM `customer_behavior.Customer`
  GROUP BY Category, `Item Purchased`
)

SELECT
  Category,
  `Item Purchased`,
  purchase_count
FROM product_counts
WHERE `Item Rank` <= 3
ORDER BY Category, purchase_count DESC;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT `Subscription Status`, count(`Customer ID`) as repeat_buyers
from `customer_behavior.Customer`
where `Previous Purchases` >5
group by `Subscription Status`;

--Q10. What is the revenue contribution of each age group?
SELECT
  CASE
    WHEN Age < 25 THEN 'Under 25'
    WHEN Age BETWEEN 25 AND 34 THEN '25–34'
    WHEN Age BETWEEN 35 AND 44 THEN '35–44'
    ELSE '45+'
  END AS age_group,
  ROUND(SUM(`Purchase_Amount`), 2) AS total_revenue
FROM `customer_behavior.Customer`
GROUP BY age_group
ORDER BY total_revenue DESC;
